import { Topic, Article } from './types';

export const NAV_LINKS = [
  { label: 'Home', view: 'HOME', path: '/' },
  { label: 'Health Topics', view: 'TOPICS', path: '/health-topics' },
  { label: 'Articles', view: 'ARTICLES', path: '/articles' },
  { label: 'Health Tools', view: 'HEALTH_TOOLS', path: '/health-tools' },
  { label: 'About Us', view: 'ABOUT', path: '/about' },
];

export const CATEGORIES = [
  { name: 'Nutrition & Diet', slug: 'nutrition-diet' },
  { name: 'Fitness & Exercise', slug: 'fitness' },
  { name: 'Mental Health', slug: 'mental-health' },
  { name: 'Heart Health', slug: 'heart-health' },
  { name: 'Sleep & Wellness', slug: 'sleep' },
  { name: 'Disease Prevention', slug: 'prevention' },
  { name: 'General Health', slug: 'general-health' },
  { name: 'Health Conditions', slug: 'health-conditions' },
  { name: 'Lifestyle & Wellness', slug: 'lifestyle-wellness' },
];

// AUTO-GENERATED from JSON files
// METADATA ONLY - Content loaded from JSON on-demand
// To add new article: Just add new .json file to public/articles/
// Then run: npm run generate-from-json
export const ARTICLES_DATA: Article[] = [
  {
    id: '10-sleep-hygiene-tips',
    title: '10 Sleep Hygiene Tips for Better Rest and Recovery',
    slug: '10-sleep-hygiene-tips-better-rest-recovery',
    excerpt: 'Master these 10 evidence-based sleep hygiene practices to improve sleep quality, wake up refreshed, and boost your overall health.',
    imageUrl: 'https://picsum.photos/id/1025/600/400',
    category: 'Sleep & Wellness',
    categorySlug: 'sleep',
    author: 'Dr. Oz Health Team',
    date: 'Dec 15, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '10 Sleep Hygiene Tips for Better Rest | Dr. Oz Health Facts',
    metaDescription: 'Improve your sleep quality with these 10 evidence-based sleep hygiene tips. Wake up refreshed and boost your health naturally.',
    metaKeywords: 'sleep hygiene, better sleep, sleep tips, insomnia, sleep quality, sleep habits, healthy sleep, sleep routine',
    schemaType: 'listicle',
    reviewRating: 4.7,
    reviewCount: 128,
    jsonPath: '/articles/10-sleep-hygiene-tips.json'
  },
  {
    id: '10-ways-boost-energy-naturally',
    title: '10 Natural Ways to Boost Energy Without Caffeine (2025 Guide)',
    slug: '10-ways-boost-energy-naturally',
    excerpt: 'Discover 10 science-backed ways to increase energy naturally without relying on caffeine. Simple, effective strategies for sustained energy all day long.',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
    category: 'General Health',
    categorySlug: 'general-health',
    author: 'Dr. Oz Health Team',
    date: 'Dec 16, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '10 Natural Ways to Boost Energy Without Caffeine (2025)',
    metaDescription: 'Tired of energy crashes? Discover 10 proven ways to boost energy naturally without caffeine. Science-backed tips for sustained energy all day.',
    metaKeywords: 'boost energy naturally, increase energy, natural energy boosters, energy without caffeine, how to get more energy, fight fatigue',
    schemaType: 'listicle',
    reviewRating: 4.8,
    reviewCount: 634,
    jsonPath: '/articles/10-ways-boost-energy-naturally.json'
  },
  {
    id: '12-superfoods-daily-diet',
    title: '12 Superfoods You Should Eat Every Day for Optimal Health (2025)',
    slug: '12-superfoods-daily-diet',
    excerpt: 'Discover 12 nutrient-dense superfoods that boost immunity, fight disease, and promote longevity. Easy ways to add them to your daily diet.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
    category: 'General Health',
    categorySlug: 'general-health',
    author: 'Dr. Oz Health Team',
    date: 'Dec 17, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '12 Superfoods to Eat Every Day for Optimal Health (2025 Guide)',
    metaDescription: 'Transform your health with these 12 superfoods. Science-backed benefits, nutrition facts, and easy ways to add them to your daily diet.',
    metaKeywords: 'superfoods, healthy foods, nutrient dense foods, superfoods list, best foods for health, anti-aging foods, immune boosting foods',
    schemaType: 'listicle',
    reviewRating: 4.9,
    reviewCount: 856,
    jsonPath: '/articles/12-superfoods-daily-diet.json'
  },
  {
    id: '5-ways-reduce-stress-naturally',
    title: '5 Proven Ways to Reduce Stress Naturally Without Medication',
    slug: '5-ways-reduce-stress-naturally-without-medication',
    excerpt: 'Discover five evidence-based natural methods to reduce stress, anxiety, and improve your mental well-being without relying on medication.',
    imageUrl: 'https://picsum.photos/id/338/600/400',
    category: 'Mental Health',
    categorySlug: 'mental-health',
    author: 'Dr. Oz Health Team',
    date: 'Dec 18, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '5 Proven Ways to Reduce Stress Naturally | Dr. Oz Health Facts',
    metaDescription: 'Discover 5 evidence-based natural methods to reduce stress and anxiety. Improve mental well-being without medication using these proven techniques.',
    metaKeywords: 'reduce stress naturally, stress relief, anxiety management, natural stress remedies, stress reduction techniques, mindfulness, meditation',
    schemaType: 'listicle',
    reviewRating: 4.7,
    reviewCount: 128,
    jsonPath: '/articles/5-ways-reduce-stress-naturally.json'
  },
  {
    id: '7-exercises-heart-health',
    title: '7 Best Exercises for Heart Health and Cardiovascular Fitness',
    slug: '7-best-exercises-heart-health-cardiovascular-fitness',
    excerpt: 'Discover the most effective exercises to strengthen your heart, improve circulation, and reduce cardiovascular disease risk.',
    imageUrl: 'https://picsum.photos/id/866/600/400',
    category: 'Fitness & Exercise',
    categorySlug: 'fitness',
    author: 'Dr. Oz Health Team',
    date: 'Dec 19, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '7 Best Exercises for Heart Health | Dr. Oz Health Facts',
    metaDescription: 'Discover the 7 most effective exercises for heart health. Strengthen your cardiovascular system and reduce heart disease risk naturally.',
    metaKeywords: 'heart health exercises, cardiovascular fitness, cardio workout, heart disease prevention, aerobic exercise, strength training',
    schemaType: 'listicle',
    reviewRating: 4.7,
    reviewCount: 128,
    jsonPath: '/articles/7-exercises-heart-health.json'
  },
  {
    id: '8-signs-dehydration',
    title: '8 Warning Signs of Dehydration You Shouldn\'t Ignore (2025 Guide)',
    slug: '8-signs-dehydration',
    excerpt: 'Learn the 8 critical warning signs of dehydration and how to prevent it. Expert guide to staying properly hydrated for optimal health and energy.',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800&h=600&fit=crop',
    category: 'General Health',
    categorySlug: 'general-health',
    author: 'Dr. Oz Health Team',
    date: 'Dec 20, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '8 Warning Signs of Dehydration You Shouldn\'t Ignore (2025)',
    metaDescription: 'Recognize the 8 critical signs of dehydration before it\'s too late. Learn symptoms, causes, prevention tips, and when to seek medical help.',
    metaKeywords: 'signs of dehydration, dehydration symptoms, how to tell if dehydrated, dehydration warning signs, prevent dehydration, hydration tips',
    schemaType: 'listicle',
    reviewRating: 4.9,
    reviewCount: 721,
    jsonPath: '/articles/8-signs-dehydration.json'
  },
  {
    id: 'best-foods-weight-loss',
    title: '25 Best Foods for Weight Loss: Science-Backed Choices That Work (2025)',
    slug: 'best-foods-weight-loss',
    excerpt: 'Discover 25 scientifically proven foods that boost metabolism, reduce hunger, and accelerate weight loss. Complete guide with nutrition facts and meal ideas.',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
    category: 'Nutrition & Diet',
    categorySlug: 'nutrition-diet',
    author: 'Dr. Oz Health Team',
    date: 'Dec 21, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '25 Best Foods for Weight Loss: Science-Backed List (2025)',
    metaDescription: 'Discover the 25 best foods for weight loss backed by science. Learn which foods boost metabolism, reduce hunger, and help you lose weight naturally.',
    metaKeywords: 'best foods for weight loss, weight loss foods, fat burning foods, metabolism boosting foods, healthy weight loss, diet foods',
    schemaType: 'itemlist',
    reviewRating: 4.9,
    reviewCount: 687,
    jsonPath: '/articles/best-foods-weight-loss.json'
  },
  {
    id: 'boost-immune-system',
    title: 'How to Boost Your Immune System Naturally',
    slug: 'boost-immune-system-naturally',
    excerpt: 'Strengthen your body\'s natural defenses with these evidence-based strategies for optimal immune health.',
    imageUrl: 'https://picsum.photos/id/493/600/400',
    category: 'Disease Prevention',
    categorySlug: 'prevention',
    author: 'Dr. Oz Health Team',
    date: 'Dec 22, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'How to Boost Your Immune System Naturally | Dr. Oz',
    metaDescription: 'Strengthen your immune system naturally with proven strategies. Expert advice on nutrition, lifestyle, and supplements for optimal immune health.',
    metaKeywords: 'boost immune system, immune health, natural immunity, immune support, wellness, disease prevention',
    schemaType: 'general',
    reviewRating: 4.8,
    reviewCount: 245,
    jsonPath: '/articles/boost-immune-system.json'
  },
  {
    id: 'common-health-questions-answered',
    title: '50 Common Health Questions Answered by Dr. Oz: Your Complete Guide (2025)',
    slug: 'common-health-questions-answered',
    excerpt: 'Get expert answers to 50 most common health questions. From nutrition and fitness to sleep and mental health - comprehensive, science-backed answers you can trust.',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop',
    category: 'General Health',
    categorySlug: 'general-health',
    author: 'Dr. Oz Health Team',
    date: 'Dec 23, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '50 Common Health Questions Answered by Dr. Oz (2025 Guide)',
    metaDescription: 'Expert answers to your most common health questions. Nutrition, fitness, sleep, mental health, and more. Science-backed advice from Dr. Oz\'s team.',
    metaKeywords: 'health questions, health answers, common health questions, health FAQ, medical questions, wellness questions, health advice',
    schemaType: 'faqpage',
    reviewRating: 4.9,
    reviewCount: 1247,
    jsonPath: '/articles/common-health-questions-answered.json'
  },
  {
    id: 'healthy-aging-after-40',
    title: 'Complete Guide to Healthy Aging After 40',
    slug: 'healthy-aging-after-40',
    excerpt: 'Discover proven strategies to maintain vitality, health, and wellness as you age gracefully after 40. Expert tips for longevity and quality of life.',
    imageUrl: 'https://picsum.photos/id/1005/600/400',
    category: 'Disease Prevention',
    categorySlug: 'prevention',
    author: 'Dr. Oz Health Team',
    date: 'Dec 24, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'Complete Guide to Healthy Aging After 40 | Dr. Oz Health Facts',
    metaDescription: 'Discover proven strategies to maintain vitality and wellness as you age gracefully after 40. Expert tips for healthy aging and longevity.',
    metaKeywords: 'healthy aging, aging after 40, anti-aging tips, longevity, wellness over 40, healthy lifestyle, aging gracefully',
    schemaType: 'general',
    reviewRating: 4.7,
    reviewCount: 128,
    jsonPath: '/articles/healthy-aging-after-40.json'
  },
  {
    id: 'healthy-morning-routine',
    title: 'The Ultimate Healthy Morning Routine: 15 Habits That Transform Your Day (2025)',
    slug: 'healthy-morning-routine',
    excerpt: 'Discover the science-backed morning routine that boosts energy, improves focus, and sets you up for success. Complete guide with step-by-step instructions.',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop',
    category: 'Lifestyle & Wellness',
    categorySlug: 'lifestyle-wellness',
    author: 'Dr. Oz Health Team',
    date: 'Dec 25, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'Healthy Morning Routine: 15 Habits for Success (2025 Guide)',
    metaDescription: 'Transform your mornings with this science-backed routine. 15 proven habits that boost energy, focus, and productivity. Start your day right!',
    metaKeywords: 'healthy morning routine, morning habits, morning routine for success, productive morning routine, wellness routine, self-care morning',
    schemaType: 'article',
    reviewRating: 4.9,
    reviewCount: 892,
    jsonPath: '/articles/healthy-morning-routine.json'
  },
  {
    id: 'healthy-smoothie-recipes',
    title: '15 Healthy Smoothie Recipes for Weight Loss and Energy (2025)',
    slug: 'healthy-smoothie-recipes',
    excerpt: 'Discover 15 delicious and nutritious smoothie recipes packed with vitamins, minerals, and antioxidants. Perfect for weight loss, energy boost, and overall health.',
    imageUrl: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800&h=600&fit=crop',
    category: 'Nutrition & Diet',
    categorySlug: 'nutrition-diet',
    author: 'Dr. Oz Health Team',
    date: 'Dec 26, 2025',
    content: '', // Content loaded from JSON
    metaTitle: '15 Healthy Smoothie Recipes for Weight Loss & Energy (2025)',
    metaDescription: 'Try these 15 delicious healthy smoothie recipes for weight loss, energy, and better health. Easy 5-minute recipes with nutrition facts. Start your day right!',
    metaKeywords: 'healthy smoothie recipes, weight loss smoothies, green smoothies, protein smoothies, breakfast smoothies, fruit smoothies, detox smoothies',
    schemaType: 'recipe',
    reviewRating: 4.8,
    reviewCount: 523,
    jsonPath: '/articles/healthy-smoothie-recipes.json'
  },
  {
    id: 'hypertension',
    title: 'Hypertension: Complete Guide to Understanding and Managing High Blood Pressure',
    slug: 'hypertension-high-blood-pressure-guide',
    excerpt: 'Comprehensive medical guide to hypertension: causes, symptoms, diagnosis, treatment options, and lifestyle management for better cardiovascular health.',
    imageUrl: 'https://picsum.photos/id/429/600/400',
    category: 'Heart Health',
    categorySlug: 'heart-health',
    author: 'Dr. Oz Health Team',
    date: 'Dec 27, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'Hypertension Guide: Causes, Symptoms & Treatment Options',
    metaDescription: 'Complete medical guide to hypertension (high blood pressure): understand causes, recognize symptoms, explore treatment options, and learn management strategies.',
    metaKeywords: 'hypertension, high blood pressure, blood pressure management, cardiovascular disease, hypertension treatment, blood pressure medication, heart health',
    schemaType: 'medical-condition',
    reviewRating: 4.8,
    reviewCount: 289,
    jsonPath: '/articles/hypertension.json'
  },
  {
    id: 'intermittent-fasting-guide',
    title: 'Intermittent Fasting: Complete Beginner\'s Guide to Weight Loss and Health',
    slug: 'intermittent-fasting-guide',
    excerpt: 'Discover how intermittent fasting can transform your health. Complete guide with meal plans, schedules, and science-backed benefits for sustainable weight loss.',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
    category: 'Nutrition & Diet',
    categorySlug: 'nutrition-diet',
    author: 'Dr. Oz Health Team',
    date: 'Dec 28, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'Intermittent Fasting Guide 2025: Lose Weight & Improve Health | Dr. Oz',
    metaDescription: 'Complete intermittent fasting guide for beginners. Learn 16:8, 5:2 methods, meal plans, benefits, and how to start safely. Science-backed weight loss results.',
    metaKeywords: 'intermittent fasting, intermittent fasting for beginners, 16:8 fasting, intermittent fasting weight loss, fasting benefits, intermittent fasting meal plan, how to start intermittent fasting, fasting schedule',
    schemaType: 'howto',
    reviewRating: 4.9,
    reviewCount: 456,
    jsonPath: '/articles/intermittent-fasting-guide.json'
  },
  {
    id: 'keto-diet-complete-guide',
    title: 'Keto Diet for Beginners: Complete Guide to Ketogenic Diet and Weight Loss',
    slug: 'keto-diet-complete-guide',
    excerpt: 'Master the ketogenic diet with this complete beginner\'s guide. Learn what to eat, meal plans, benefits, and how to enter ketosis safely for rapid weight loss.',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&h=600&fit=crop',
    category: 'Nutrition & Diet',
    categorySlug: 'nutrition-diet',
    author: 'Dr. Oz Health Team',
    date: 'Dec 29, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'Keto Diet Guide 2025: Lose Weight Fast with Ketogenic Diet | Dr. Oz',
    metaDescription: 'Complete keto diet guide for beginners. Learn ketogenic diet basics, food lists, meal plans, and how to start keto safely. Achieve rapid weight loss results.',
    metaKeywords: 'keto diet, ketogenic diet, keto for beginners, keto meal plan, ketosis, keto diet plan, low carb diet, keto foods, how to start keto, keto weight loss',
    schemaType: 'howto',
    reviewRating: 4.8,
    reviewCount: 523,
    jsonPath: '/articles/keto-diet-complete-guide.json'
  },
  {
    id: 'lose-belly-fat-fast',
    title: 'How to Lose Belly Fat Fast: 15 Science-Backed Methods That Actually Work',
    slug: 'lose-belly-fat-fast',
    excerpt: 'Discover proven strategies to lose stubborn belly fat quickly and safely. Science-backed methods including diet, exercise, and lifestyle changes for a flatter stomach.',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=600&fit=crop',
    category: 'Weight Loss',
    categorySlug: 'lifestyle-wellness',
    author: 'Dr. Oz Health Team',
    date: 'Dec 30, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'How to Lose Belly Fat Fast in 2025: 15 Proven Methods | Dr. Oz',
    metaDescription: 'Learn how to lose belly fat fast with 15 science-backed methods. Includes diet plans, exercises, and lifestyle tips for rapid, sustainable results.',
    metaKeywords: 'how to lose belly fat, lose belly fat fast, belly fat loss, reduce belly fat, flat stomach, abdominal fat, visceral fat, belly fat exercises, belly fat diet',
    schemaType: 'howto',
    reviewRating: 4.9,
    reviewCount: 892,
    jsonPath: '/articles/lose-belly-fat-fast.json'
  },
  {
    id: 'lower-blood-pressure-naturally',
    title: 'How to Lower Blood Pressure Naturally: Complete Step-by-Step Guide',
    slug: 'lower-blood-pressure-naturally',
    excerpt: 'Learn proven, natural methods to reduce high blood pressure without medication. Expert-backed strategies for better heart health and longevity.',
    imageUrl: 'https://picsum.photos/id/429/600/400',
    category: 'Heart Health',
    categorySlug: 'heart-health',
    author: 'Dr. Oz Health Team',
    date: 'Dec 31, 2025',
    content: '', // Content loaded from JSON
    metaTitle: 'How to Lower Blood Pressure Naturally | Step-by-Step Guide',
    metaDescription: 'Discover 10 proven natural methods to lower blood pressure without medication. Expert tips, diet plans, and lifestyle changes for better heart health.',
    metaKeywords: 'lower blood pressure naturally, reduce hypertension, natural blood pressure remedies, heart health, high blood pressure treatment, DASH diet, blood pressure control',
    schemaType: 'howto',
    reviewRating: 4.8,
    reviewCount: 245,
    jsonPath: '/articles/lower-blood-pressure-naturally.json'
  },
  {
    id: 'mental-wellness-daily-habits',
    title: 'Mental Wellness: Daily Habits for Better Mental Health',
    slug: 'mental-wellness-daily-habits-better-health',
    excerpt: 'Discover simple daily habits that can transform your mental health and emotional well-being. Evidence-based strategies for a healthier mind.',
    imageUrl: 'https://picsum.photos/id/342/600/400',
    category: 'Mental Health',
    categorySlug: 'mental-health',
    author: 'Dr. Oz Health Team',
    date: 'Jan 1, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Mental Wellness: Daily Habits for Better Mental Health | Dr. Oz',
    metaDescription: 'Transform your mental health with these evidence-based daily habits. Simple strategies for better emotional well-being and mental wellness.',
    metaKeywords: 'mental wellness, mental health, daily habits, emotional well-being, mindfulness, stress management, mental health tips, self-care',
    schemaType: 'general',
    reviewRating: 4.7,
    reviewCount: 128,
    jsonPath: '/articles/mental-wellness-daily-habits.json'
  },
  {
    id: 'start-mediterranean-diet',
    title: 'How to Start a Mediterranean Diet: Complete Beginner\'s Guide',
    slug: 'how-to-start-mediterranean-diet-complete-guide',
    excerpt: 'Learn how to start and maintain a Mediterranean diet with this step-by-step guide. Discover meal plans, shopping lists, and proven health benefits.',
    imageUrl: 'https://picsum.photos/id/1080/600/400',
    category: 'Nutrition & Diet',
    categorySlug: 'nutrition-diet',
    author: 'Dr. Oz Health Team',
    date: 'Jan 2, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'How to Start a Mediterranean Diet: Complete Guide | Dr. Oz',
    metaDescription: 'Start the Mediterranean diet with this complete beginner\'s guide. Step-by-step instructions, meal plans, shopping lists, and proven health benefits.',
    metaKeywords: 'Mediterranean diet, how to start Mediterranean diet, Mediterranean diet plan, healthy eating, heart-healthy diet, Mediterranean diet benefits',
    schemaType: 'howto',
    reviewRating: 4.9,
    reviewCount: 189,
    jsonPath: '/articles/start-mediterranean-diet.json'
  },
  {
    id: 'top-10-anti-inflammatory-foods',
    title: 'Top 10 Anti-Inflammatory Foods to Add to Your Diet',
    slug: 'top-10-anti-inflammatory-foods-diet',
    excerpt: 'Discover the most powerful anti-inflammatory foods that can reduce chronic inflammation and boost your overall health naturally.',
    imageUrl: 'https://picsum.photos/id/1080/600/400',
    category: 'Nutrition & Diet',
    categorySlug: 'nutrition-diet',
    author: 'Dr. Oz Health Team',
    date: 'Jan 3, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Top 10 Anti-Inflammatory Foods to Add to Your Diet | Dr. Oz',
    metaDescription: 'Discover the 10 most powerful anti-inflammatory foods. Reduce chronic inflammation naturally with these evidence-based dietary choices.',
    metaKeywords: 'anti-inflammatory foods, inflammation, chronic inflammation, healthy diet, superfoods, nutrition, anti-inflammatory diet',
    schemaType: 'listicle',
    reviewRating: 4.7,
    reviewCount: 128,
    jsonPath: '/articles/top-10-anti-inflammatory-foods.json'
  },
  {
    id: 'type-2-diabetes',
    title: 'Type 2 Diabetes: Complete Guide to Prevention, Management, and Living Well',
    slug: 'type-2-diabetes-prevention-management',
    excerpt: 'Comprehensive guide to understanding, preventing, and managing Type 2 diabetes. Expert advice on symptoms, treatment, diet, and lifestyle changes.',
    imageUrl: 'https://picsum.photos/id/1005/600/400',
    category: 'Disease Prevention',
    categorySlug: 'prevention',
    author: 'Dr. Oz Health Team',
    date: 'Jan 4, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Type 2 Diabetes Guide: Prevention, Symptoms & Management',
    metaDescription: 'Complete guide to Type 2 diabetes: symptoms, causes, prevention strategies, treatment options, and lifestyle management. Expert medical advice.',
    metaKeywords: 'type 2 diabetes, diabetes prevention, diabetes symptoms, blood sugar control, diabetes management, prediabetes, insulin resistance, diabetes diet',
    schemaType: 'medical-condition',
    reviewRating: 4.9,
    reviewCount: 312,
    jsonPath: '/articles/type-2-diabetes.json'
  },
  {
    id: 'understanding-anxiety-disorders',
    title: 'Understanding Anxiety Disorders: Symptoms, Causes, and Treatment Options (2025)',
    slug: 'understanding-anxiety-disorders',
    excerpt: 'Comprehensive guide to anxiety disorders including symptoms, causes, types, and evidence-based treatments. Learn how to manage anxiety effectively.',
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&h=600&fit=crop',
    category: 'Health Conditions',
    categorySlug: 'health-conditions',
    author: 'Dr. Oz Health Team',
    date: 'Jan 5, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Anxiety Disorders: Symptoms, Causes & Treatment Guide (2025)',
    metaDescription: 'Complete guide to anxiety disorders. Learn about symptoms, causes, types (GAD, panic disorder, social anxiety), and effective treatments including therapy and lifestyle changes.',
    metaKeywords: 'anxiety disorders, anxiety symptoms, generalized anxiety disorder, panic disorder, social anxiety, anxiety treatment, how to manage anxiety',
    schemaType: 'medical-condition',
    reviewRating: 4.9,
    reviewCount: 1043,
    jsonPath: '/articles/understanding-anxiety-disorders.json'
  },
  {
    id: 'understanding-arthritis',
    title: 'Understanding Arthritis: Types, Symptoms, and Treatment Options (2025 Guide)',
    slug: 'understanding-arthritis',
    excerpt: 'Complete guide to arthritis including osteoarthritis and rheumatoid arthritis. Learn about symptoms, causes, diagnosis, and effective treatments for joint pain relief.',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&h=600&fit=crop',
    category: 'Health Conditions',
    categorySlug: 'health-conditions',
    author: 'Dr. Oz Health Team',
    date: 'Jan 6, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Arthritis Guide: Types, Symptoms & Treatment Options (2025)',
    metaDescription: 'Comprehensive arthritis guide covering osteoarthritis, rheumatoid arthritis, symptoms, causes, and treatments. Expert advice for managing joint pain and improving quality of life.',
    metaKeywords: 'arthritis, osteoarthritis, rheumatoid arthritis, joint pain, arthritis symptoms, arthritis treatment, arthritis relief, joint inflammation',
    schemaType: 'medical-condition',
    reviewRating: 4.8,
    reviewCount: 892,
    jsonPath: '/articles/understanding-arthritis.json'
  },
  {
    id: 'understanding-asthma',
    title: 'Understanding Asthma: Symptoms, Triggers, and Management Strategies (2025)',
    slug: 'understanding-asthma',
    excerpt: 'Comprehensive asthma guide covering symptoms, triggers, types, and effective management strategies. Learn how to control asthma and live an active life.',
    imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=800&h=600&fit=crop',
    category: 'Health Conditions',
    categorySlug: 'health-conditions',
    author: 'Dr. Oz Health Team',
    date: 'Jan 7, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Asthma Guide: Symptoms, Triggers & Management (2025)',
    metaDescription: 'Complete asthma guide with symptoms, triggers, types, and management strategies. Expert advice for controlling asthma and preventing attacks.',
    metaKeywords: 'asthma, asthma symptoms, asthma triggers, asthma attack, asthma treatment, asthma management, asthma inhaler, breathing problems',
    schemaType: 'medical-condition',
    reviewRating: 4.9,
    reviewCount: 967,
    jsonPath: '/articles/understanding-asthma.json'
  },
  {
    id: 'understanding-cholesterol',
    title: 'Understanding Cholesterol: Good vs Bad - Complete Guide',
    slug: 'understanding-cholesterol-good-vs-bad',
    excerpt: 'Learn the difference between good and bad cholesterol, how to manage your levels, and protect your heart health naturally.',
    imageUrl: 'https://picsum.photos/id/429/600/400',
    category: 'Heart Health',
    categorySlug: 'heart-health',
    author: 'Dr. Oz Health Team',
    date: 'Jan 8, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Understanding Cholesterol: Good vs Bad | Dr. Oz Health Facts',
    metaDescription: 'Learn the difference between HDL and LDL cholesterol. Expert guide to managing cholesterol levels naturally for better heart health.',
    metaKeywords: 'cholesterol, HDL, LDL, good cholesterol, bad cholesterol, heart health, cholesterol management, lower cholesterol naturally',
    schemaType: 'general',
    reviewRating: 4.7,
    reviewCount: 128,
    jsonPath: '/articles/understanding-cholesterol.json'
  },
  {
    id: 'understanding-gerd',
    title: 'Understanding GERD: Symptoms, Causes, and Effective Treatment Options (2025)',
    slug: 'understanding-gerd',
    excerpt: 'Comprehensive GERD guide covering acid reflux symptoms, causes, diagnosis, and treatments. Learn how to manage heartburn and prevent complications naturally.',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
    category: 'General Health',
    categorySlug: 'general-health',
    author: 'Dr. Oz Health Team',
    date: 'Jan 9, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'GERD Guide: Symptoms, Causes & Treatment (2025)',
    metaDescription: 'Complete GERD and acid reflux guide. Learn about symptoms, causes, diagnosis, and effective treatments for heartburn and gastroesophageal reflux disease.',
    metaKeywords: 'GERD, acid reflux, heartburn, GERD symptoms, GERD treatment, acid reflux relief, gastroesophageal reflux disease, heartburn remedies',
    schemaType: 'medical-condition',
    reviewRating: 4.8,
    reviewCount: 923,
    jsonPath: '/articles/understanding-gerd.json'
  },
  {
    id: 'understanding-insomnia',
    title: 'Understanding Insomnia: Causes, Symptoms, and Effective Treatment Solutions (2025)',
    slug: 'understanding-insomnia',
    excerpt: 'Comprehensive insomnia guide covering causes, symptoms, types, and evidence-based treatments. Learn how to overcome sleep problems and get restful sleep naturally.',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop',
    category: 'General Health',
    categorySlug: 'general-health',
    author: 'Dr. Oz Health Team',
    date: 'Jan 10, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Insomnia Guide: Causes, Symptoms & Treatment (2025)',
    metaDescription: 'Complete insomnia guide with causes, symptoms, and effective treatments. Expert advice for overcoming sleep problems and achieving restful, quality sleep.',
    metaKeywords: 'insomnia, sleep problems, insomnia treatment, insomnia causes, sleep disorders, how to sleep better, insomnia remedies, chronic insomnia',
    schemaType: 'medical-condition',
    reviewRating: 4.9,
    reviewCount: 1156,
    jsonPath: '/articles/understanding-insomnia.json'
  },
  {
    id: 'understanding-migraines',
    title: 'Understanding Migraines: Symptoms, Triggers, and Relief Strategies (2025)',
    slug: 'understanding-migraines',
    excerpt: 'Comprehensive migraine guide covering symptoms, triggers, types, and effective treatment options. Learn how to prevent and manage debilitating migraine headaches.',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=600&fit=crop',
    category: 'General Health',
    categorySlug: 'general-health',
    author: 'Dr. Oz Health Team',
    date: 'Jan 11, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Migraine Guide: Symptoms, Triggers & Treatment (2025)',
    metaDescription: 'Complete migraine guide with symptoms, triggers, and relief strategies. Expert advice for preventing and managing migraine headaches effectively.',
    metaKeywords: 'migraines, migraine headaches, migraine symptoms, migraine triggers, migraine treatment, migraine relief, chronic migraines, headache relief',
    schemaType: 'medical-condition',
    reviewRating: 4.8,
    reviewCount: 834,
    jsonPath: '/articles/understanding-migraines.json'
  },
  {
    id: 'yoga-for-beginners',
    title: 'Yoga for Beginners: Complete Guide to Start Your Practice at Home',
    slug: 'yoga-for-beginners',
    excerpt: 'Start your yoga journey with this complete beginner\'s guide. Learn basic poses, breathing techniques, and how to practice yoga safely at home for flexibility and stress relief.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
    category: 'Fitness & Exercise',
    categorySlug: 'fitness',
    author: 'Dr. Oz Health Team',
    date: 'Jan 12, 2026',
    content: '', // Content loaded from JSON
    metaTitle: 'Yoga for Beginners 2025: Start Your Practice at Home | Dr. Oz',
    metaDescription: 'Complete yoga guide for beginners. Learn basic poses, breathing techniques, and how to start yoga at home. Improve flexibility, reduce stress, and boost health.',
    metaKeywords: 'yoga for beginners, yoga poses, yoga at home, beginner yoga, yoga benefits, how to start yoga, yoga breathing, yoga for flexibility, yoga for stress',
    schemaType: 'howto',
    reviewRating: 4.9,
    reviewCount: 678,
    jsonPath: '/articles/yoga-for-beginners.json'
  }
];

export const TOPICS_DATA: Topic[] = [
  {
    id: 'nutrition',
    title: 'Nutrition & Diet',
    description: 'Eat smart for better health',
    iconName: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
    slug: 'nutrition-diet'
  },
  {
    id: 'fitness',
    title: 'Fitness & Exercise',
    description: 'Stay active and fit',
    iconName: 'Dumbbell',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
    slug: 'fitness'
  },
  {
    id: 'mental',
    title: 'Mental Health',
    description: 'Your mind matters',
    iconName: 'Brain',
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&h=600&fit=crop',
    slug: 'mental-health'
  },
  {
    id: 'heart',
    title: 'Heart Health',
    description: 'Keep your heart strong',
    iconName: 'HeartPulse',
    imageUrl: 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=800&h=600&fit=crop',
    slug: 'heart-health'
  },
  {
    id: 'sleep',
    title: 'Sleep & Wellness',
    description: 'Rest and recover better',
    iconName: 'Moon',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop',
    slug: 'sleep'
  },
  {
    id: 'prevention',
    title: 'Disease Prevention',
    description: 'Your armor against illness',
    iconName: 'ShieldPlus',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=600&fit=crop',
    slug: 'prevention'
  },
  {
    id: 'general-health',
    title: 'General Health',
    description: 'Essential health tips for everyone',
    iconName: 'Activity',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&h=600&fit=crop',
    slug: 'general-health'
  },
  {
    id: 'health-conditions',
    title: 'Health Conditions',
    description: 'Understanding common health issues',
    iconName: 'Stethoscope',
    imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=800&h=600&fit=crop',
    slug: 'health-conditions'
  },
  {
    id: 'lifestyle-wellness',
    title: 'Lifestyle & Wellness',
    description: 'Daily habits for better living',
    iconName: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop',
    slug: 'lifestyle-wellness'
  }
];
